package registroaulas.view;

import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import registroaulas.db.connectionDB;
import registroaulas.model.RegistroAulaModel;

/**
 *
 * @author joseluiz
 */
public class CadastroAulaView extends javax.swing.JFrame {

    /**
     * imprtações do model e criação de variaveis para diretórios
     */
    RegistroAulaModel registroAulaModel = new RegistroAulaModel();
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form CadastroAulaView
     *
     * @throws java.io.FileNotFoundException
     */
    public CadastroAulaView() throws FileNotFoundException {
        initComponents();
        setLocationRelativeTo(null);
        habilitarCampos(false);
        limparCampos();
        setarData();
        conn = connectionDB.conexaoBD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfTema = new javax.swing.JTextField();
        jtfTextoBase = new javax.swing.JTextField();
        jtfOrdem = new javax.swing.JTextField();
        jtfDinamica = new javax.swing.JTextField();
        jtfData = new javax.swing.JTextField();
        jcbStatus = new javax.swing.JComboBox<>();
        jcbRendimento = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtfObs = new javax.swing.JTextArea();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jbRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Regsitro Aulas Evangelização FECMA");

        jPanel1.setBackground(new java.awt.Color(52, 49, 72));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TEMA");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TEXTO BASE (ROTEIRO FEB)");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("N° ORDEM");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATA");

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("STATUS");

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RENDIMENTO");

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DINÂMICA UTILIZADA");

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("OBSERVAÇÕES GERAIS");

        jtfTema.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jtfTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTemaActionPerformed(evt);
            }
        });

        jtfTextoBase.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N

        jtfOrdem.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N

        jtfDinamica.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N

        jtfData.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N

        jcbStatus.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OK", "PENDENTE", "CANCELADA" }));
        jcbStatus.setToolTipText("");
        jcbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbStatusActionPerformed(evt);
            }
        });

        jcbRendimento.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jcbRendimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOM", "MÉDIO", "RUIM" }));
        jcbRendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbRendimentoActionPerformed(evt);
            }
        });

        jtfObs.setColumns(20);
        jtfObs.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jtfObs.setRows(5);
        jScrollPane1.setViewportView(jtfObs);

        jbSalvar.setBackground(new java.awt.Color(185, 58, 50));
        jbSalvar.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbCancelar.setBackground(new java.awt.Color(0, 110, 109));
        jbCancelar.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbNovo.setBackground(new java.awt.Color(43, 87, 151));
        jbNovo.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbRegistro.setText("Ver Registros Salvos");
        jbRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfTema, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jtfTextoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(71, 71, 71)
                                        .addComponent(jLabel5))))
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfDinamica, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfData, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbRendimento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfOrdem)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSalvar)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTema, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTextoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDinamica, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfData, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbRendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar)
                    .addComponent(jbCancelar)
                    .addComponent(jbNovo)
                    .addComponent(jbRegistro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTemaActionPerformed
    }//GEN-LAST:event_jtfTemaActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        habilitarCampos(true);
        jtfTema.requestFocus();
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        habilitarCampos(false);
        limparCampos();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        try {
            salvarRegistro();
            limparCampos();
            jtfTema.requestFocus();
        } catch (IOException ex) {
            Logger.getLogger(CadastroAulaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jcbRendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbRendimentoActionPerformed
        alterarCoresRendimento();
    }//GEN-LAST:event_jcbRendimentoActionPerformed

    private void jcbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbStatusActionPerformed
        alterarCoresStatus();
    }//GEN-LAST:event_jcbStatusActionPerformed

    private void jbRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistroActionPerformed
        try {
            (new ListarAulasView()).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(CadastroAulaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbRegistroActionPerformed

    /**
     * habilitar ou desabilitar os campos de inserção
     *
     * @param condicao
     */
    private void habilitarCampos(boolean condicao) {
        jtfData.setEnabled(condicao);
        jtfDinamica.setEnabled(condicao);
        jtfObs.setEnabled(condicao);
        jtfOrdem.setEnabled(condicao);
        jtfTema.setEnabled(condicao);
        jtfTextoBase.setEnabled(condicao);
        jbCancelar.setEnabled(condicao);
        jbSalvar.setEnabled(condicao);
        jcbRendimento.setEnabled(condicao);
        jcbStatus.setEnabled(condicao);
    }

    /**
     * metodo para limpar os campos após salvar ou cancelar o registro
     */
    private void limparCampos() {
        jtfDinamica.setText("");
        jtfObs.setText("");
        jtfOrdem.setText("");
        jtfTema.setText("");
        jtfTextoBase.setText("");
        jcbRendimento.setSelectedItem("BOM");
        jcbStatus.setSelectedItem("OK");

    }

    /**
     * metodo que insere a data atual no campo data no frame
     */
    private void setarData() {
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yy");
        LocalDateTime timepoint = LocalDateTime.now();
        jtfData.setText(timepoint.format(fmt));
    }

    /**
     * metodo para atribuir os dados vindos da tela para o model salvar os dados
     * no model em um arquivo
     *
     * @throws IOException
     */
    private void salvarRegistro() throws IOException {

        if (jtfObs.getText().equals("")) {
            registroAulaModel.setObservacoesGerais("NENHUMA OBSERVAÇÃO DISPONIVEL.");
        } else {
            registroAulaModel.setObservacoesGerais(jtfObs.getText().toUpperCase());
        }
        registroAulaModel.setData(jtfData.getText());
        registroAulaModel.setDinamicaUtilizada(jtfDinamica.getText().toUpperCase());
        registroAulaModel.setNumeroOrdem(jtfOrdem.getText());
        registroAulaModel.setRendimento(jcbRendimento.getSelectedItem().toString());
        registroAulaModel.setStatus(jcbStatus.getSelectedItem().toString());
        registroAulaModel.setTema(jtfTema.getText().toUpperCase());
        registroAulaModel.setTextoBase(jtfTextoBase.getText().toUpperCase());
        inserirRegistro();
    }

    /**
     * metodo para alterar as cores do comboBox rendimento
     */
    private void alterarCoresRendimento() {
        if (jcbRendimento.getSelectedItem().equals("BOM")) {
            jcbRendimento.setBackground(new java.awt.Color(30, 113, 69));
            jcbRendimento.setForeground(new java.awt.Color(255, 255, 255));
        }
        if (jcbRendimento.getSelectedItem().equals("MÉDIO")) {
            jcbRendimento.setBackground(new java.awt.Color(43, 87, 151));
            jcbRendimento.setForeground(new java.awt.Color(255, 255, 255));
        }
        if (jcbRendimento.getSelectedItem().equals("RUIM")) {
            jcbRendimento.setBackground(new java.awt.Color(185, 29, 71));
            jcbRendimento.setForeground(new java.awt.Color(255, 255, 255));
        }

    }

    /**
     * metódo para alterar as cores do comboBox Status
     */
    private void alterarCoresStatus() {
        if (jcbStatus.getSelectedItem().equals("OK")) {
            jcbStatus.setBackground(new java.awt.Color(30, 113, 69));
            jcbStatus.setForeground(new java.awt.Color(255, 255, 255));
        }
        if (jcbStatus.getSelectedItem().equals("PENDENTE")) {
            jcbStatus.setBackground(new java.awt.Color(227, 162, 26));
            jcbStatus.setForeground(new java.awt.Color(255, 255, 255));
        }
        if (jcbStatus.getSelectedItem().equals("CANCELADA")) {
            jcbStatus.setBackground(new java.awt.Color(185, 29, 71));
            jcbStatus.setForeground(new java.awt.Color(255, 255, 255));
        }
    }

    private void inserirRegistro() {
        try {
            String insert = "INSERT INTO tb_tema(tema, texto_base,num_ordem,dinamica,data,status,rendimento,observacoes) VALUES (?,?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(insert);
            pst.setString(1, registroAulaModel.getTema());
            pst.setString(2, registroAulaModel.getTextoBase());
            pst.setString(3, registroAulaModel.getNumeroOrdem());
            pst.setString(4, registroAulaModel.getDinamicaUtilizada());
            pst.setString(5, registroAulaModel.getData());
            pst.setString(6, registroAulaModel.getStatus());
            pst.setString(7, registroAulaModel.getRendimento());
            pst.setString(8, registroAulaModel.getObservacoesGerais());
            pst.execute();
            JOptionPane.showMessageDialog(this, "Registro Salvo com sucesso");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar os dados do registro: " + e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbRegistro;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox<String> jcbRendimento;
    private javax.swing.JComboBox<String> jcbStatus;
    private javax.swing.JTextField jtfData;
    private javax.swing.JTextField jtfDinamica;
    private javax.swing.JTextArea jtfObs;
    private javax.swing.JTextField jtfOrdem;
    private javax.swing.JTextField jtfTema;
    private javax.swing.JTextField jtfTextoBase;
    // End of variables declaration//GEN-END:variables
}
